'use client';

import { useEffect, useState } from 'react';

type Analytics = { configured: boolean; period?: string; visitors?: number; sessions?: number; conversions?: number; conversionRate?: number; newsletter?: number; socialClicks?: number; timeline?: Array<Record<string, string | number>>; dailyViews?: Array<Record<string, string | number>>; monthlyViews?: Array<Record<string, string | number>>; yearlyViews?: Array<Record<string, string | number>>; pages?: Array<Record<string, string | number>>; sources?: Array<Record<string, string | number>>; devices?: Array<Record<string, string | number>>; countries?: Array<Record<string, string | number>>; };

export default function AnalyticsPage() {
  const [analytics, setAnalytics] = useState<Analytics | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch('/api/admin/analytics', { cache: 'no-store' }).then(async (response) => { const data = await response.json() as Analytics & { error?: string; details?: string }; if (!response.ok) throw new Error([data.error, data.details].filter(Boolean).join(' ')); setAnalytics(data); }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Analytics indisponibles.')); }, []);
  return <div className="mx-auto max-w-7xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-600">Mesure du site</p><h1 className="mt-2 text-3xl font-black text-slate-950">Analytics</h1><p className="mt-2 text-sm text-slate-600">{analytics?.period || 'Données GA4 et événements JcHub'}</p></header>{error && <Notice text={error} />}{analytics && !analytics.configured && <Notice text="GA4 n’est pas encore connecté. Ajoute GA4_PROPERTY_ID et un compte de service Google autorisé sur la propriété." />}{analytics?.configured && <><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{[['Visiteurs', analytics.visitors], ['Sessions', analytics.sessions], ['Conversions', analytics.conversions], ['Taux de conversion', `${analytics.conversionRate}%`], ['Inscriptions newsletter', analytics.newsletter], ['Clics sociaux', analytics.socialClicks]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p></div>)}</div><LineChart title="Visiteurs et sessions" rows={analytics.timeline || []} /><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black text-slate-950">Vues des pages</h2><p className="mt-1 text-sm text-slate-500">Nombre de pages consultées, regroupé par période.</p><div className="mt-5 grid gap-5 lg:grid-cols-3"><BarChart title="Par jour · 365 jours" rows={analytics.dailyViews || []} label="date" metric="screenPageViews" color="#4f46e5" /><BarChart title="Par mois · 2 ans" rows={analytics.monthlyViews || []} label="yearMonth" metric="screenPageViews" color="#0891b2" /><BarChart title="Par année · 5 ans" rows={analytics.yearlyViews || []} label="year" metric="screenPageViews" color="#059669" /></div></section><div className="grid gap-5 lg:grid-cols-2"><BarChart title="Pages les plus consultées" rows={analytics.pages || []} label="pagePath" metric="screenPageViews" color="#4f46e5" /><BarChart title="Provenance des visiteurs" rows={analytics.sources || []} label="sessionSourceMedium" metric="sessions" color="#0891b2" /><BarChart title="Appareils" rows={analytics.devices || []} label="deviceCategory" metric="activeUsers" color="#059669" /><BarChart title="Pays" rows={analytics.countries || []} label="country" metric="activeUsers" color="#ea580c" /></div></>}</div>;
}

function BarChart({ title, rows, label, metric, color }: { title: string; rows: Array<Record<string, string | number>>; label: string; metric: string; color: string }) { const visible = rows.slice(0, 8); const max = Math.max(...visible.map((row) => Number(row[metric] || 0)), 1); return <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-slate-950">{title}</h2><div className="mt-5 space-y-4">{visible.length ? visible.map((row, index) => { const value = Number(row[metric] || 0); return <div key={`${String(row[label])}-${index}`}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="max-w-[75%] truncate text-slate-600">{String(row[label])}</span><strong className="text-slate-950">{value.toLocaleString('fr-FR')}</strong></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: `${Math.max((value / max) * 100, value ? 3 : 0)}%`, backgroundColor: color }} /></div></div>; }) : <p className="text-sm text-slate-500">Aucune donnée.</p>}</div></section>; }
function LineChart({ title, rows }: { title: string; rows: Array<Record<string, string | number>> }) { const values = rows.map((row) => Number(row.activeUsers || 0)); const sessions = rows.map((row) => Number(row.sessions || 0)); const max = Math.max(...values, ...sessions, 1); const points = (series: number[]) => series.map((value, index) => `${(index / Math.max(series.length - 1, 1)) * 100},${100 - (value / max) * 88}`).join(' '); return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold text-slate-950">{title}</h2><div className="flex gap-4 text-xs text-slate-600"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-indigo-600" />Visiteurs</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-cyan-600" />Sessions</span></div></div>{rows.length ? <div className="mt-5 h-64"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="h-52 w-full overflow-visible" role="img" aria-label="Évolution des visiteurs et sessions"><line x1="0" y1="100" x2="100" y2="100" stroke="#e2e8f0" strokeWidth="0.5" /><polyline points={points(values)} fill="none" stroke="#4f46e5" strokeWidth="1.4" vectorEffect="non-scaling-stroke" /><polyline points={points(sessions)} fill="none" stroke="#0891b2" strokeWidth="1.4" vectorEffect="non-scaling-stroke" /></svg><div className="flex justify-between text-[10px] text-slate-400"><span>{String(rows[0]?.date || '')}</span><span>{String(rows[rows.length - 1]?.date || '')}</span></div></div> : <p className="mt-5 text-sm text-slate-500">Aucune donnée.</p>}</section>; }
function Notice({ text }: { text: string }) { return <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{text}</div>; }