import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, BookOpen, Check, Code2, FileText, Headphones, ShieldCheck, Sparkles, Wrench } from 'lucide-react';
import { books } from '@/lib/books';
import { tools } from '@/lib/tools';
import { getAdminDb, hasFirebaseAdminConfig } from '@/lib/firebase-admin';
import { formatXAF } from '@/lib/pricing';
import { Newsletter } from '@/components/Newsletter';

export const dynamic = 'force-dynamic';

export default async function HomePage() {
  let published: any[] = [];

  if (hasFirebaseAdminConfig()) {
    try {
      const snapshot = await getAdminDb()
        .collection('books')
        .where('status', '==', 'available')
        .get();
      published = snapshot.docs.map((document) => document.data());
    } catch {
      /* The static catalogue remains a safe local fallback. */
    }
  }

  const catalogue = published.length ? published : books;
  const featuredBooks = catalogue.filter((book) => book.status === 'available').slice(0, 3);

  return <div className="home-page bg-white text-slate-900">
    <section className="home-hero relative overflow-hidden border-b border-slate-200 bg-[#f7f8fa]"><div className="home-hero-grid absolute inset-0" /><div className="home-hero-glow home-hero-glow-one" /><div className="home-hero-glow home-hero-glow-two" /><div className="relative mx-auto grid max-w-6xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:py-28">
      <div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-slate-600"><Sparkles className="h-3.5 w-3.5 text-orange-500" /> APPRENDRE AUTREMENT</p><h1 className="max-w-3xl text-4xl font-black leading-[1.05] tracking-tight sm:text-6xl">Des outils simples.<br /><span className="text-orange-600">De vraies compétences.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-600">JcHub réunit des outils pratiques et une bibliothèque de ressources pour progresser, sans se perdre.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/compte" className="inline-flex items-center gap-2 rounded-xl bg-[#17324d] px-5 py-3 font-bold text-white transition hover:bg-orange-600">Créer mon espace <ArrowRight className="h-4 w-4" /></Link><Link href="/outils" className="rounded-xl border border-slate-300 bg-white px-5 py-3 font-bold text-slate-700 transition hover:border-slate-500">Voir les outils</Link></div></div>
      <div className="home-hero-art relative flex min-h-[360px] items-center justify-center sm:min-h-[440px]"><Image src="/header-hero.png" alt="Une personne apprenant avec JcHub" width={768} height={768} priority className="relative z-10 h-auto w-full max-w-[33rem] object-contain drop-shadow-[0_24px_28px_rgba(23,50,77,0.14)]" /><div className="home-float-card home-float-card-top"><Code2 className="h-4 w-4 text-teal-600" />Build smarter</div><div className="absolute bottom-2 left-0 z-20 rounded-xl border border-slate-200 bg-white/95 px-4 py-3 shadow-lg"><div className="text-xs font-bold text-orange-600">JCHUB</div><div className="text-sm font-bold">Apprendre à ton rythme</div></div></div>
    </div></section>

    <section className="home-quick-links border-b border-slate-200 bg-[#112333] text-white"><div className="mx-auto grid max-w-6xl gap-2 px-4 py-3 sm:grid-cols-3 sm:px-6"><Link href="/outils" className="group flex items-center gap-3 p-3 transition hover:bg-white/10"><Wrench className="h-5 w-5 text-orange-300" /><span><strong className="block text-sm">Outils gratuits</strong><small className="text-xs text-slate-400">Résoudre maintenant</small></span><ArrowRight className="ml-auto h-4 w-4 transition group-hover:translate-x-1" /></Link><Link href="/livres/pdf" className="group flex items-center gap-3 p-3 transition hover:bg-white/10"><FileText className="h-5 w-5 text-orange-300" /><span><strong className="block text-sm">Livres PDF</strong><small className="text-xs text-slate-400">Lire et télécharger</small></span><ArrowRight className="ml-auto h-4 w-4 transition group-hover:translate-x-1" /></Link><Link href="/livres/audio" className="group flex items-center gap-3 p-3 transition hover:bg-white/10"><Headphones className="h-5 w-5 text-teal-300" /><span><strong className="block text-sm">Livres audio</strong><small className="text-xs text-slate-400">Écouter autrement</small></span><ArrowRight className="ml-auto h-4 w-4 transition group-hover:translate-x-1" /></Link></div></section>

    <section className="home-section mx-auto max-w-6xl px-4 py-20 sm:px-6"><SectionTitle eyebrow="OUTILS PRATIQUES" title="Ce dont tu as besoin, sans distraction." action="Tous les outils" href="/outils" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tools.slice(0, 3).map((tool, index) => <Link href={`/outils/${tool.slug}`} key={tool.slug} style={{ animationDelay: `${index * 70}ms` }} className="home-card group rounded-2xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:border-teal-300 hover:shadow-xl"><div className="mb-5 grid h-12 w-12 place-items-center rounded-xl bg-orange-50 text-3xl transition group-hover:rotate-3 group-hover:scale-110">{tool.icon}</div><h2 className="font-bold group-hover:text-orange-600">{tool.name}</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">{tool.description}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-orange-600">Utiliser <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></section>

    <section className="border-y border-slate-200 bg-[#f7f8fa]"><div className="mx-auto max-w-6xl px-4 py-20 sm:px-6"><SectionTitle eyebrow="BIBLIOTHÈQUE" title="Choisis ton prochain sujet." action="Explorer les livres" href="/livres" /><div className="grid gap-5 md:grid-cols-3">{featuredBooks.map((book) => <Link href={`/livres/${book.slug}`} key={book.slug} className="overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative flex aspect-[16/10] items-end bg-[#17324d] p-5">{book.cover && <img src={book.cover} alt="" className="absolute inset-0 h-full w-full object-cover" />}<span className="relative rounded-full bg-white/90 px-2.5 py-1 text-xs font-bold text-slate-800">{book.pricing === 'free' ? 'Gratuit' : formatXAF(book.oneTimePriceXAF)}</span></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-orange-600">{book.category}</p><h2 className="mt-2 font-bold">{book.title}</h2><p className="mt-1 text-sm text-slate-500">{book.author}</p></div></Link>)}</div></div></section>

    <section className="mx-auto max-w-6xl px-4 py-20 sm:px-6"><SectionTitle eyebrow="COMMENT ÇA MARCHE" title="Une expérience pensée pour aller à l’essentiel." action="Créer un compte" href="/compte" /><div className="grid gap-5 md:grid-cols-3"><Step number="01" title="Explore" text="Trouve un outil ou une ressource adaptée à ton objectif du moment." icon={<Wrench />} /><Step number="02" title="Utilise" text="Travaille directement dans le navigateur, lis ou télécharge tes documents." icon={<Code2 />} /><Step number="03" title="Progresse" text="Garde tes ressources et ton activité dans ton espace personnel." icon={<Check />} /></div></section>

    <section className="border-y border-slate-200 bg-[#f7f8fa]"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-20 sm:px-6 lg:grid-cols-2"><div><p className="text-xs font-bold tracking-widest text-orange-600">POURQUOI JCHUB</p><h2 className="mt-3 text-3xl font-black">Une plateforme utile, sans surplus.</h2><p className="mt-4 max-w-lg leading-relaxed text-slate-600">Nous privilégions des contenus accessibles, des outils concrets et une navigation qui te laisse te concentrer sur ton apprentissage.</p></div><div className="space-y-4"><Benefit text="Des outils gratuits utilisables immédiatement" /><Benefit text="Des guides et documents à télécharger" /><Benefit text="Une bibliothèque qui évolue avec les nouvelles publications" /><Benefit text="Un compte unique pour retrouver ton espace" /></div></div></section>

    <section className="mx-auto max-w-6xl px-4 py-20 text-center sm:px-6"><p className="text-xs font-bold tracking-widest text-orange-600">ILS NOUS SOUTIENNENT</p><h2 className="mt-3 text-3xl font-black">Construisons l’apprentissage numérique ensemble.</h2><p className="mx-auto mt-4 max-w-2xl text-slate-600">JcHub est ouvert aux écoles, communautés, entreprises et créateurs qui souhaitent rendre les compétences numériques plus accessibles.</p><div className="mt-10 grid gap-4 sm:grid-cols-2"><Partner name="GitHub" logo="/partners/github.svg" /><Partner name="2MD Designer" logo="/partners/2md-designer.svg" /></div><Link href="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-[#17324d] hover:text-orange-600">Devenir partenaire <ArrowRight className="h-4 w-4" /></Link></section>

    <section className="bg-[#17324d] px-4 py-20 text-center text-white sm:px-6"><p className="text-xs font-bold tracking-widest text-orange-300">NEWSLETTER</p><h2 className="mt-3 text-3xl font-black">Une dose utile, pas de bruit.</h2><p className="mx-auto mt-3 max-w-xl text-slate-300">Nouveaux outils, ressources ajoutées et conseils pratiques : directement dans ta boîte mail.</p><Newsletter /><p className="mt-4 text-xs text-slate-400">Tu peux te désinscrire à tout moment.</p></section>

    <section className="mx-auto max-w-6xl px-4 py-20 sm:px-6"><div className="rounded-3xl bg-[#17324d] px-6 py-12 text-white sm:px-12"><p className="text-sm font-bold text-orange-300">UN ESPACE, À TA MESURE</p><h2 className="mt-3 max-w-2xl text-3xl font-black sm:text-4xl">Crée ton compte et commence avec les outils gratuits.</h2><p className="mt-4 max-w-xl text-slate-300">Ton tableau de bord garde tes ressources à portée de main.</p><Link href="/compte" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 font-bold text-white hover:bg-orange-400">Commencer gratuitement <ArrowRight className="h-4 w-4" /></Link></div></section>
  </div>;
}

function Metric({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-orange-50 text-orange-600">{icon}</span><div><div className="font-black">{value}</div><div className="text-sm text-slate-500">{label}</div></div></div>; }
function SectionTitle({ eyebrow, title, action, href }: { eyebrow: string; title: string; action: string; href: string }) { return <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-widest text-orange-600">{eyebrow}</p><h2 className="mt-2 text-3xl font-black">{title}</h2></div><Link href={href} className="inline-flex items-center gap-1 text-sm font-bold text-slate-700 hover:text-orange-600">{action} <ArrowRight className="h-4 w-4" /></Link></div>; }
function Step({ number, title, text, icon }: { number: string; title: string; text: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-slate-200 p-6"><div className="flex items-center justify-between"><span className="text-sm font-black text-orange-600">{number}</span><span className="text-slate-400">{icon}</span></div><h3 className="mt-8 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-500">{text}</p></div>; }
function Benefit({ text }: { text: string }) { return <div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-700"><ShieldCheck className="h-5 w-5 shrink-0 text-orange-600" />{text}</div>; }
function Partner({ name, logo }: { name: string; logo: string }) { return <div className="group grid min-h-36 place-items-center rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:-translate-y-1 hover:border-orange-300 hover:bg-orange-50 hover:shadow-lg"><img src={logo} alt={`Logo ${name}`} className="h-28 w-full object-contain transition duration-300 group-hover:scale-[1.03]" /></div>; }
