import { ArrowDown, FileText, FolderOpen, Layers3, Sparkles } from 'lucide-react';
import { FormatCatalog } from '@/components/books/FormatCatalog';
import { getAvailableBooks } from '@/lib/book-catalog';

export const metadata = { title: 'Livres PDF pour apprendre et progresser', description: 'Découvre et télécharge des livres PDF en français sur le développement, les réseaux, Python, Java et la cybersécurité.', keywords: ['livres PDF', 'livres informatiques PDF', 'cours programmation PDF', 'livres développement'], alternates: { canonical: '/livres/pdf' }, openGraph: { title: 'Livres PDF · JcHub', description: 'Des ressources PDF utiles pour apprendre le développement et les technologies.', url: '/livres/pdf', type: 'website' } };
export const dynamic = 'force-dynamic';

export default async function PdfBooksPage() {
  const books = await getAvailableBooks();
  return <main className="pdf-page min-h-screen bg-[#f5f7f5] text-slate-950"><section className="pdf-hero relative overflow-hidden bg-[#112333] px-4 py-14 text-white sm:px-6 lg:px-8 lg:py-20"><div className="pdf-grid absolute inset-0 opacity-30" /><div className="pdf-glow pdf-glow-one" /><div className="pdf-glow pdf-glow-two" /><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_380px] lg:items-center"><div className="pdf-hero-copy"><div className="mb-5 inline-flex items-center gap-2 border border-orange-300/30 bg-orange-300/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.18em] text-orange-200"><FileText className="h-4 w-4" /> Bibliothèque PDF</div><h1 className="max-w-3xl text-5xl font-black leading-[.92] tracking-tight sm:text-7xl">Ouvre un fichier.<br /><span className="text-orange-300">Ferme une boucle.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Des PDF utiles, propres et prêts à accompagner ton prochain projet. Trouve une ressource, consulte ses détails et garde-la avec toi.</p><div className="mt-8 flex flex-wrap items-center gap-5 text-sm font-bold text-slate-300"><span className="inline-flex items-center gap-2"><FolderOpen className="h-4 w-4 text-teal-300" />{books.length} ressources</span><span className="inline-flex items-center gap-2"><Layers3 className="h-4 w-4 text-orange-300" />PDF sélectionnés</span></div></div><div className="pdf-stack" aria-hidden="true"><div className="pdf-sheet pdf-sheet-back" /><div className="pdf-sheet pdf-sheet-mid" /><div className="pdf-sheet pdf-sheet-front"><div className="flex items-center justify-between text-orange-500"><FileText className="h-8 w-8" /><Sparkles className="h-5 w-5" /></div><div className="mt-14 h-2 w-24 bg-slate-200" /><div className="mt-3 h-2 w-36 bg-slate-100" /><div className="mt-8 space-y-2"><div className="h-1.5 w-full bg-slate-100" /><div className="h-1.5 w-5/6 bg-slate-100" /><div className="h-1.5 w-3/4 bg-slate-100" /></div><div className="absolute bottom-5 right-5 rounded-full bg-orange-500 px-3 py-1 text-[10px] font-black text-white">READ / BUILD</div></div><ArrowDown className="pdf-arrow absolute -bottom-4 -left-4 h-8 w-8 text-orange-300" /></div></div></section><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8 lg:py-14"><div className="mb-8 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">Le rayon numérique</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Choisis ton prochain PDF</h2></div><div className="hidden text-right text-sm text-slate-500 sm:block">Lecture claire.<br /><span className="font-bold text-slate-900">Accès selon ton offre.</span></div></div><FormatCatalog books={books} format="pdf" /></section></main>;
}
