import { AudioLines, Headphones, Mic2, Radio, Sparkles } from 'lucide-react';
import { FormatCatalog } from '@/components/books/FormatCatalog';
import { getAvailableBooks } from '@/lib/book-catalog';

export const metadata = { title: 'Livres audio pour développeurs', description: 'Écoute des livres audio en français sur la programmation, les réseaux, la cybersécurité et la technologie.', keywords: ['livres audio', 'livres audio développement', 'livres audio programmation', 'livres audio français'], alternates: { canonical: '/livres/audio' }, openGraph: { title: 'Livres audio · JcHub', description: 'Une collection de livres audio pour apprendre autrement.', url: '/livres/audio', type: 'website' } };
export const dynamic = 'force-dynamic';

export default async function AudioBooksPage() {
  const books = await getAvailableBooks();
  return <main className="audio-page min-h-screen bg-[#0d1724] text-white"><section className="audio-hero relative overflow-hidden border-b border-white/10 px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="audio-grid absolute inset-0 opacity-20" /><div className="audio-glow audio-glow-one" /><div className="audio-glow audio-glow-two" /><div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_400px] lg:items-center"><div className="animate-page-in"><div className="mb-5 inline-flex items-center gap-2 border border-teal-300/30 bg-teal-300/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.18em] text-teal-200"><Headphones className="h-4 w-4" /> Collection audio</div><h1 className="max-w-3xl text-5xl font-black leading-[.92] tracking-tight sm:text-7xl">Des idées<br /><span className="text-teal-300">dans les oreilles.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Des livres audio pour apprendre en marchant, en travaillant ou entre deux idées. Découvre chaque univers avant de choisir ton accès.</p><div className="mt-8 flex flex-wrap gap-5 text-sm font-bold text-slate-300"><span className="inline-flex items-center gap-2"><Radio className="h-4 w-4 text-orange-300" />{books.length} sessions à découvrir</span><span className="inline-flex items-center gap-2"><Mic2 className="h-4 w-4 text-teal-300" />Écoute premium</span></div></div><div className="audio-console" aria-hidden="true"><div className="audio-console-top"><span className="flex items-center gap-2"><span className="audio-dot" /> NOW PLAYING</span><AudioLines className="h-4 w-4 text-teal-300" /></div><div className="audio-disc"><div className="audio-disc-center"><Headphones className="h-8 w-8" /></div></div><div className="audio-wave">{Array.from({ length: 25 }, (_, index) => <span key={index} style={{ animationDelay: `${index * 55}ms`, height: `${18 + ((index * 17) % 48)}%` }} />)}</div><div className="mt-5 flex items-center justify-between text-xs text-slate-400"><span>JcHub / audio library</span><Sparkles className="h-4 w-4 text-orange-300" /></div></div></div></section><section className="audio-library mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8 lg:py-14"><div className="mb-8 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-teal-300">Le rayon à écouter</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Choisis ton prochain audio</h2></div><div className="hidden text-right text-sm text-slate-400 sm:block">Informations d’abord.<br /><span className="font-bold text-white">Accès ensuite.</span></div></div><FormatCatalog books={books} format="audio" /></section></main>;
}
