import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Check, Headphones, Lock, ShoppingCart } from 'lucide-react';
import { getAvailableBooks, hasAudio } from '@/lib/book-catalog';
import { formatXAF } from '@/lib/pricing';

export const dynamic = 'force-dynamic';

export default async function AudioBookDetailPage({ params }: { params: { slug: string } }) {
  const book = (await getAvailableBooks()).find((item) => item.slug === params.slug) as Record<string, any> | undefined;
  if (!book || !hasAudio(book)) notFound();
  const price = Number(book.oneTimePriceXAF || 0);
  const isFree = book.pricing === 'free';

  return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/livres/audio" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4" /> Retour aux livres audio</Link><section className="mt-8 grid gap-10 lg:grid-cols-[280px_1fr] lg:items-start"><div className="relative aspect-[4/5] overflow-hidden rounded-2xl bg-gradient-to-br from-teal-500 to-orange-500 shadow-2xl">{book.cover ? <img src={book.cover} alt={`Couverture de ${book.title}`} className="h-full w-full object-cover" /> : <Headphones className="m-auto h-16 w-16 text-white/80" />}<span className="absolute left-3 top-3 bg-white px-2 py-1 text-xs font-black text-slate-950">AUDIO</span></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-orange-300">Livre audio · {book.category || 'Ressource'}</p><h1 className="mt-3 text-4xl font-black leading-tight sm:text-6xl">{book.title}</h1><p className="mt-3 text-lg text-slate-300">par <strong className="text-white">{book.author || 'JcHub'}</strong></p><p className="mt-7 max-w-2xl text-base leading-8 text-slate-300">{book.description || 'Les informations détaillées de ce livre audio seront bientôt disponibles.'}</p><div className="mt-8 grid max-w-lg grid-cols-2 gap-3 sm:grid-cols-3"><div className="border border-white/10 bg-white/5 p-4"><Headphones className="mb-3 h-5 w-5 text-teal-300" /><p className="text-xs text-slate-400">Durée estimée</p><p className="mt-1 font-black">{book.estimatedAudioHours || 0} h</p></div><div className="border border-white/10 bg-white/5 p-4"><Check className="mb-3 h-5 w-5 text-emerald-300" /><p className="text-xs text-slate-400">Chapitres</p><p className="mt-1 font-black">{book.totalChapters || 1}</p></div><div className="border border-white/10 bg-white/5 p-4"><Lock className="mb-3 h-5 w-5 text-orange-300" /><p className="text-xs text-slate-400">Accès</p><p className="mt-1 font-black">{isFree ? 'Libre' : 'Premium'}</p></div></div><div className="mt-8 border border-orange-300/20 bg-orange-300/10 p-5"><p className="font-bold">L’écoute complète et le téléchargement sont protégés.</p><p className="mt-2 text-sm leading-6 text-slate-300">Abonne-toi à JcHub+ pour accéder au catalogue, ou achète ce livre à l’unité.</p><div className="mt-5 flex flex-col gap-3 sm:flex-row">{!isFree && <Link href={`/checkout?plan=book&book=${book.slug}&price=${price}`} className="inline-flex items-center justify-center gap-2 bg-orange-500 px-5 py-3 text-sm font-black text-slate-950 hover:bg-orange-300"><ShoppingCart className="h-4 w-4" /> Acheter {formatXAF(price)}</Link>}<Link href="/pricing" className="inline-flex items-center justify-center gap-2 border border-white/20 px-5 py-3 text-sm font-bold hover:bg-white/10">Voir les abonnements</Link></div></div></div></section></div></main>;
}
